const colors = {
  light: {
    text: "#1C1C1E",
    tint: "#1C1C1E",
    background: "#F7FAFF",
    foreground: "#1C1C1E",
    card: "#FFFFFF",
    cardForeground: "#1C1C1E",
    primary: "#1C1C1E",
    primaryForeground: "#FFFFFF",
    secondary: "#F2F2F7",
    secondaryForeground: "#1C1C1E",
    muted: "#F2F2F7",
    mutedForeground: "#8E8E93",
    accent: "#FF6B00",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#E8ECF4",
    input: "#E8ECF4",
    success: "#34C759",
    blue: "#007AFF",
  },
  dark: {
    text: "#EBEBF5",
    tint: "#EBEBF5",
    background: "#000000",
    foreground: "#EBEBF5",
    card: "#1C1C1E",
    cardForeground: "#EBEBF5",
    primary: "#EBEBF5",
    primaryForeground: "#1C1C1E",
    secondary: "#2C2C2E",
    secondaryForeground: "#EBEBF5",
    muted: "#2C2C2E",
    mutedForeground: "#8E8E93",
    accent: "#FF6B00",
    accentForeground: "#FFFFFF",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#38383A",
    input: "#38383A",
    success: "#30D158",
    blue: "#0A84FF",
  },
  radius: 18,
};

export default colors;
